apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: icinga2
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: main/monitoring/icinga2
    repoURL: {{ .Values.repo.url }}
    targetRevision: {{ .Values.repo.revision }}
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
