apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: cloudflare-ddns-secret
  namespace: default
spec:
  path: secrets/main/homelab/cloudflare-ddns/cloudflare-ddns-secret
  type: Opaque
