apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudflare-ddns.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudflare-ddns.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "script/*").AsConfig | indent 2 }}
