apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: alertmanager-discord-secret
  namespace: monitoring
spec:
  path: secrets/main/monitoring/alertmanager-discord/alertmanager-discord-secret
  type: Opaque
