node-feature-discovery:
  image:
    repository: raspbernetes/node-feature-discovery
    tag: "v0.9.0"
  sources:
    # - cpu
    - custom
    # - iommu
    # - kernel
    # - local
    # - memory
    # - network
    - pci
    # - storage
    # - system
    - usb
  # node-feature-discovery configuration - see https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/nfd-worker.conf.example for example
  config: |
    sources:
      usb:
        deviceClassWhitelist:
          - "02"
          - "0e"
          - "ef"
          - "fe"
          - "ff"
        deviceLabelFields:
          - "class"
          - "vendor"
          - "device"
      custom:
        - name: "zwave"
          matchOn:
            - usbId:
                class: ["ff"]
                vendor: ["10c4"]
                device: ["8a2a"]
        - name: "zigbee"
          matchOn:
            - usbId:
                class: ["ff"]
                vendor: ["10c4"]
                device: ["8a2a"]
  #          - name: "coral-tpu"
  #            matchOn:
  #              - usbId:
  #                  vendor: ["1a6e", "18d1"]
  #          - name: "intel-gpu"
  #            matchOn:
  #              - pciId:
  #                  class: ["0300"]
  #                  vendor: ["8086"]
  master:
    replicaCount: 1
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      - key: arm
        operator: Exists
      - key: arm64
        operator: Exists
  worker:
    tolerations:
      - key: arm
        operator: Exists
      - key: arm64
        operator: Exists
