node-feature-discovery:
  nodeFeatureRule:
    createCRD: true

  worker:
    config:
      core:
        sources:
          - custom
          - pci
          - usb
      sources:
        usb:
          deviceClassWhitelist:
            - "02"
            - "03"
            - "0e"
            - "ef"
            - "fe"
            - "ff"
          deviceLabelFields:
            - "class"
            - "vendor"
            - "device"
        custom:
          - name: "zwave"
            matchOn:
              - usbId:
                  class: ["ff"]
                  vendor: ["10c4"]
                  device: ["8a2a"]
          - name: "zigbee"
            matchOn:
              - usbId:
                  class: ["ff"]
                  vendor: ["10c4"]
                  device: ["8a2a"]
          - name: "ati-radeon"
            matchOn:
              - pciId:
                  class: ["0300"]
                  vendor: ["1002"]
          - name: "nvidia-geforce"
            matchOn:
              - pciId:
                  class: ["0300"]
                  vendor: ["10de"]
          - name: "intel-gpu"
            matchOn:
              - pciId:
                  class: ["0300"]
                  vendor: ["8086"]
          - name: "coral-tpu"
            matchOn:
              - usbId:
                  vendor: ["1a6e", "18d1"]

    annotations:
      configmap.reloader.stakater.com/reload: "nfd-worker-conf"
    tolerations:
#      - key: arm
#        operator: Exists
      - key: arm64
        operator: Exists
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
#      - effect: "NoExecute"
#        operator: "Exists"
      - effect: "NoSchedule"
        operator: "Exists"
  master:
    replicaCount: 1
    tolerations:
#      - key: arm
#        operator: Exists
      - key: arm64
        operator: Exists

