longhorn:
  persistence:
    defaultClassReplicaCount: 3
  defaultSettings:
    defaultReplicaCount: 3
    createDefaultDiskLabeledNodes: true
#    backupTarget: s3://longhorn@minio/backups
#    backupTargetCredentialSecret: longhorn-backup-secret
    storageMinimalAvailablePercentage: "10"
  ingress:
    enabled: true
    host: longhorn.rsr.net

