statping:
  image:
    repository: statping/statping
    tag: "v0.90.74"

  postgresql:
    # -- By default uses an internal postgress. Disable if you use your own Postgres.
    enabled: false

  # See more environment variables in the statping documentation
  # https://github.com/statping/statping/wiki/Config-with-.env-File
  env:
    NAME: RSR Statping
    DESCRIPTION: RSR Home Lab Status
    VIRTUAL_HOST: "stats.rsr.net"
    # -- dashboard admin email
    ADMIN_EMAIL: rogerrum@gmail.com
    DB_DATABASE: "statping"
    DB_USER: "statping"
    DISABLE_LOGS: true

  #  envValueFrom:
  #    DB_PASS:
  #      secretKeyRef:
  #        name: statping-secret
  #        key: DB_PASS
  #    DB_HOST:
  #      secretKeyRef:
  #        name: statping-secret
  #        key: DB_HOST
  #    ADMIN_PASSWORD:
  #      secretKeyRef:
  #        name: statping-secret
  #        key: DB_HOST

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: vault-issuer
      cert-manager.io/common-name: stats.rsr.net
    hosts:
      - host: stats.rsr.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - stats.rsr.net
        secretName: stats-cert-tls

  # cert is needed for accessing the sites
  additionalVolumeMounts:
    - name: tls-cert
      mountPath: "/etc/ssl"
      subPath: "ca.crt"
      readOnly: true

  additionalVolumes:
    - name: tls-cert
      secret:
        secretName: stats-cert-tls
        items:
          - key: "ca.crt"
            path: certs/
