thanos:
  # image:
  #   repository: quay.io/thanos/thanos
  #   tag: v0.15.0
  query:
    replicaCount: 2
    replicaLabels:
      - replica
    http:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
#          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"
#          nginx.ingress.kubernetes.io/auth-url: "https://auth.rsr.net/oauth2/auth"
#          nginx.ingress.kubernetes.io/auth-signin: https://auth.rsr.net/oauth2/start
        hosts: [ "thanos.rsr.net" ]
#        tls:
#          - hosts: [ "thanos.rsr.net" ]
  compact:
    retentionResolution1h: 5y
  objstore:
    type: S3
    config:
      bucket: "thanos"
      endpoint: "minio.default.svc:9000"
      region: ""
      insecure: true
      signature_version2: false
      put_user_metadata: { }
      http_config:
        idle_conn_timeout: 0s
        response_header_timeout: 0s
        insecure_skip_verify: false
      trace:
        enable: false
      part_size: 0
