thanos:
  query:
    enabled: true
    replicaCount: 2
    replicaLabels:
      - replica
    dnsDiscovery:
      sidecarsService: kube-prometheus-stack-thanos-discovery
      sidecarsNamespace: monitoring
    ingress:
      enabled: true
      hostname: thanos.rsr.net
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: vault-issuer
        cert-manager.io/common-name: thanos.rsr.net
        nginx.ingress.kubernetes.io/auth-url: "https://auth.rsr.net/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.rsr.net/oauth2/start"
      tls: true
  queryFrontend:
    enabled: false
  bucketweb:
    enabled: true
  compactor:
    enabled: true
    persistence:
      enabled: false
  storegateway:
    enabled: true
    persistence:
      enabled: true
      size: 7Gi
  ruler:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
