mealie:
  image:
    repository: hkotel/mealie
    tag: v0.5.1
  env:
    TZ: "America/Chicago"
    DB_TYPE: postgres
    DB_ENGINE: postgres # Optional: 'sqlite', 'postgres'
    POSTGRES_USER: mealie
    POSTGRES_SERVER: postgresql.kube-system.svc.cluster.local
    POSTGRES_PORT: 5432
    POSTGRES_DB: mealie

  envValueFrom:
    POSTGRES_PASSWORD:
      secretKeyRef:
        name: mealie-secret
        key: POSTGRES_PASSWORD

  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: vault-issuer
        cert-manager.io/common-name: food.rsr.net
      hosts:
        - host: food.rsr.net
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - food.rsr.net
          secretName: mealie-cert-tls
  persistence:
    config:
      enabled: true
      storageClass: "longhorn"
      accessMode: ReadWriteOnce
      size: "1Gi"
      skipuninstall: true
