apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  keys:
    - slack-token
  path: secrets/argocd/argocd-slack-token
  type: Opaque
