homer:
  image:
    repository: b4bz/homer
    tag: 21.03.1
    env:
      TZ: "America/Chicago"
    service:
      port:
        port: 8080
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: vault-issuer
        cert-manager.io/common-name: home.rsr.net
      hosts:
        - host: home.rsr.net
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - home.rsr.net
          secretName: homer-cert-tls
    persistence:
      config:
        enabled: true
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: "1Gi"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.9.0
        workingDir: "/www/assets"
        args:
          - --user-data-dir
          - "/www/assets/.vscode"
          - --auth
          - "none"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: vault-issuer
            cert-manager.io/common-name: home-config.rsr.net
          hosts:
            - host: home-config.rsr.net
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - home-config.rsr.net
              secretName: homer-config-cert-tls
        volumeMounts:
          - name: config
            mountPath: /www/assets
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
        cpu: 2000m
