home-assistant:

  ingress:
    main:
      hosts:
        - host: $HASS_EXTERNAL_URL
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "$HASS_EXTERNAL_URL"
  addons:
    codeserver:
      env:
        HASS_SERVER: http://localhost:8123
        HASS_TOKEN: $HASS_TOKEN
