apiVersion: v1
kind: Namespace
metadata:
  name: system-upgrade
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: system-upgrade/
    repoURL: {{ .Values.repo.url }}
    targetRevision: {{ .Values.repo.revision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
