apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: oauth2-proxy-secret
  namespace: kube-system
spec:
  path: secrets/infrastructure/oauth2-proxy/oauth2-proxy-secret
  type: Opaque
