minio:
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2021-11-24T23-19-33Z

  mcImage:
    repository: quay.io/minio/mc
    tag: RELEASE.2021-11-16T20-37-36Z

  mode: gateway

  persistence:
    existingClaim: "nas-data-pvc"
    subPath: "minio"

  consoleIngress:
    enabled: true

    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: vault-issuer
      cert-manager.io/common-name: minio-test.rsr.net
    hosts: [ minio-test.rsr.net ]
    tls:
      - hosts:
          - minio-test.rsr.net
        secretName: minio-test-cert-tls
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: release
                operator: In
                values:
                  - minio-test
          topologyKey: "kubernetes.io/hostname"

  resources:
    requests:
      memory: 350Mi
      cpu: 25m
    limits:
      memory: 1000Mi
  securityContext:
    enabled: false
  metrics:
    serviceMonitor:
      enabled: true

  gateway:
    replicas: 3

  rootUser: "user"
  rootPassword: "password"

#  existingSecret: minio-secret
