apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: kured-discord-secret
  namespace: kube-system
spec:
  keys:
    - discord-token
  path: secrets/kured/kured-discord-token
  type: Opaque
