organizr:
  env:
    TZ: "America/Chicago"

  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: vault-issuer
        cert-manager.io/common-name: org.rsr.net
#        nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.kube-system.svc.cluster.local:80/oauth2/auth"
#        nginx.ingress.kubernetes.io/auth-signin: https://auth.rsr.net/oauth2/start
      hosts:
        - host: org.rsr.net
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - org.rsr.net
          secretName: org-cert-tls

  persistence:
    data:
      enabled: false
#      storageClass: "longhorn"
#      accessMode: ReadWriteOnce
#      size: "1Gi"
#      skipuninstall: true
