zwave2mqtt:
  image:
    repository: robertslando/zwave2mqtt
    tag: 4.1.1
  env:
    TZ: "America/Chicago"
    OZW_AUTO_UPDATE_CONFIG: true
  securityContext:
    privileged: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: vault-issuer
      cert-manager.io/common-name: zwave2mqtt.rsr.net
#      nginx.ingress.kubernetes.io/auth-url: "https://auth.rsr.net/oauth2/auth"
#      nginx.ingress.kubernetes.io/auth-signin: https://auth.rsr.net/oauth2/start
    hosts:
      - host: zwave2mqtt.rsr.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - "zwave2mqtt.rsr.net"
        secretName: zwave2mqtt-cert
  persistence:
    config:
      enabled: true
      mountPath: /usr/src/app/store
      existingClaim: zwave2mqtt
#      storageClass: "longhorn"
#      accessMode: ReadWriteOnce
#      size: "1Gi"
  podAnnotations:
    backup.velero.io/backup-volumes: config
  additionalVolumeMounts:
    - name: usb
      mountPath: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C130101F-if00-port0
  additionalVolumes:
    - name: usb
      hostPath:
        path: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C130101F-if00-port0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - { key: "feature.node.kubernetes.io/custom-zwave", operator: In, values: [ "true" ] }
  tolerations:
    - key: "arm"
      operator: "Exists"
