apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system
spec:
  path: secrets/infrastructure/longhorn/longhorn-backup-secret
  type: Opaque
