oauth2-proxy:
  image:
    repository: "quay.io/oauth2-proxy/oauth2-proxy"
    tag: "v7.0.1"
  replicaCount: 2
  # tolerations:
  #   - key: "arm"
  #     operator: "Exists"
  ingress:
    enabled: true
    path: /oauth2
    hosts: [ auth.rsr.net ]
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: vault-issuer
      cert-manager.io/common-name: auth.rsr.net
    tls:
      - hosts:
          - auth.rsr.net
        secretName: oauth2-proxy-cert-tls
  extraArgs:
    provider: oidc
    oidc-issuer-url: "https://rogerrum.us.auth0.com/"
    skip-provider-button:
    pass-authorization-header:
    email-domain: "*"
    cookie-domain: ".rsr.net"
    whitelist-domain: ".rsr.net"

  config:
    existingSecret: oauth2-proxy-secret
