apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    app.kubernetes.io/instance: frigate
    app.kubernetes.io/name: frigate
  name: frigate-noauth
  namespace: default
spec:
  rules:
    - host: 8003v.techbuzzworld.com
      http:
        paths:
          - path: /api/events/.*/clip\.mp4
            pathType: Prefix
            backend:
              service:
                name: frigate
                port:
                  number: 80
          - path: /api/events/.*/thumbnail\.jpg
            pathType: Prefix
            backend:
              service:
                name: frigate
                port:
                  number: 80
          - path: /api/events/.*/snapshot\.jpg
            pathType: Prefix
            backend:
              service:
                name: frigate
                port:
                  number: 80
  tls:
    - hosts:
        - 8003v.techbuzzworld.com
