clarkson:
  image:
    repository: ghcr.io/linuxserver/clarkson
    tag: "v1.1.2-ls12"

  env:
    TZ: "America/Chicago"
    ENABLE_REGISTRATIONS: true
    MYSQL_HOST: mysql.kube-system.svc.cluster.local

  secret:
    MYSQL_USERNAME: clarkson

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: vault-issuer
      cert-manager.io/common-name: clarkson.rsr.net
    hosts:
      - host: "clarkson.rsr.net"
        paths:
          - path: "/"
            pathType: Prefix
    tls:
      - hosts:
        - clarkson.rsr.net
        secretName: clarkson-cert-tls
