cert-manager:
  installCRDs: true
  webhook:
    enabled: true
    tolerations:
      - key: "arm"
        operator: "Exists"
      - key: "arm64"
        operator: "Exists"
  extraArgs:
    - --dns01-recursive-nameservers=1.1.1.1:53
    - --dns01-recursive-nameservers-only
  tolerations:
    - key: "arm"
      operator: "Exists"
    - key: "arm64"
      operator: "Exists"
  cainjector:
    replicaCount: 1
    # extraArgs:
    #   - --leader-elect=false
    tolerations:
      - key: "arm"
        operator: "Exists"
      - key: "arm64"
        operator: "Exists"
    prometheus:
    enabled: true
    servicemonitor:
      enabled: true
      prometheusInstance: monitoring
