traccar:
  image:
    repository: traccar/traccar
    tag: "4.13"
  env:
    TZ: "America/Chicago"
    DATABASE_DRIVER: "org.postgresql.Driver"
    DATABASE_URL: jdbc:postgresql://postgresql.kube-system.svc.cluster.local:5432/traccar
    DATABASE_USER: traccar
    DATABASE_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: traccar-secret
          key: DATABASE_PASSWORD


  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: vault-issuer
        cert-manager.io/common-name: traccar.rsr.net
      hosts:
        - host: traccar.rsr.net
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - traccar.rsr.net
          secretName: traccar-cert-tls
