node-red:
  image:
    repository: nodered/node-red
    tag: 1.2.9-12-minimal
  env:
    TZ: "America/Chicago"
    FLOWS: "flows.json"
    NODE_RED_ENABLE_PROJECTS: "true"
    NODE_RED_ENABLE_SAFE_MODE: "false"
  ingress:
    enabled: true
    annotations:
#      kubernetes.io/ingress.class: "nginx"
#      nginx.ingress.kubernetes.io/auth-url: "https://auth.rsr.net/oauth2/auth"
#      nginx.ingress.kubernetes.io/auth-signin: https://auth.rsr.net/oauth2/start
    hosts:
      - host: node-red.rsr.net
        paths:
          - path: /
            pathType: Prefix
#    tls:
#      - hosts:
#          - "node-red.rsr.net"
  persistence:
    data:
      enabled: true
      mountPath: /data
      storageClass: "longhorn"
      accessMode: ReadWriteOnce
      size: "5Gi"
  podAnnotations:
    backup.velero.io/backup-volumes: data
  tolerations:
    - key: "arm"
      operator: "Exists"
  resources:
    requests:
      memory: 350Mi
      cpu: 25m
    limits:
      memory: 500Mi
