apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infrastructure/descheduler
    repoURL: {{ .Values.repo.url }}
    targetRevision: {{ .Values.repo.revision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
