apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: kured-helm-values
  namespace: kube-system
spec:
  keys:
    - values
  path: secrets/infrastructure/kured/kured-helm-values
  type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infrastructure/kured
    repoURL: {{ .Values.repo.url }}
    targetRevision: {{ .Values.repo.revision }}
    plugin:
      name: secret-to-helm
      env:
        - name: SECRET_NAME
          value: "kured-helm-values"
        - name: SECRET_NAMESPACE
          value: "kube-system"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
