icinga2:
  image:
    repository: jordan/icinga2
    tag: latest

  env:
    TZ: "America/Chicago"
    DEFAULT_MYSQL_HOST: mariadb.kube-system.svc.cluster.local
    DEFAULT_MYSQL_USER: icinga2
    DEFAULT_MYSQL_PASS:
      valueFrom:
        secretKeyRef:
          name: icinga2-secret
          key: ICINGA2_MARIADB_PASS
    ICINGA2_FEATURE_DIRECTOR_PASS:
      valueFrom:
        secretKeyRef:
          name: icinga2-secret
          key: ICINGA2_FEATURE_DIRECTOR_PASS
    ICINGAWEB2_ADMIN_PASS:
      valueFrom:
        secretKeyRef:
          name: icinga2-secret
          key: ICINGAWEB2_ADMIN_PASS
    MYSQL_ROOT_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: icinga2-secret
          key: MYSQL_ROOT_PASSWORD

  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: vault-issuer
        cert-manager.io/common-name: icinga.rsr.net
      hosts:
        - host: icinga.rsr.net
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - icinga.rsr.net
          secretName: icinga-cert-tls
