kube-cleanup-operator:
  rbac:
    create: true
    global: true
  args:
    - --delete-failed-after=60m
    - --delete-successful-after=60m
    - --delete-pending-pods-after=60m
    - --delete-evicted-pods-after=60m
    - --delete-orphaned-pods-after=60m
    - --legacy-mode=false
