apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: clarkson-helm-values
  namespace: default
spec:
  keys:
    - values
  path: secrets/main/homelab/clarkson/clarkson-helm-values
  type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clarkson
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: main/homelab/clarkson
    repoURL: {{ .Values.repo.url }}
    targetRevision: {{ .Values.repo.revision }}
    plugin:
      name: secret-to-helm
      env:
        - name: SECRET_NAME
          value: "clarkson-helm-values"
        - name: SECRET_NAMESPACE
          value: "default"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
