apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zwavejs2mqtt
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: main/homelab/zwavejs2mqtt
    repoURL: {{ .Values.repo.url }}
    targetRevision: {{ .Values.repo.revision }}
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
{{/*      selfHeal: true*/}}
    syncOptions:
      - CreateNamespace=true
