apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: unifi-poller-secret
  namespace: monitoring
spec:
  path: secrets/main/monitoring/unifi-poller/unifi-poller-secret
  type: Opaque
