apiVersion: v2
appVersion: v1.0.0
description: alertmanager-discord
name: alertmanager-discord
version: 0.0.1
keywords:
  - alertmanager
  - discord
#home: https://github.com/...
#icon: https://github.com/..
sources:
- https://github.com/benjojo/alertmanager-discord
- https://hub.docker.com/r/benjojo/alertmanager-discord
maintainers:
  - name: rogerrum
    email: rogerrum@gmail.com
dependencies:
  - name: common
    version: 3.1.0
    repository: https://k8s-at-home.com/charts/
