vernemq:
  image:
    repository: vernemq/vernemq
    tag: 1.11.0-alpine
  replicaCount: 1
  serviceMonitor:
    create: true
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.100.50
    ws:
      enabled: true
  statefulset:
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8888"
  additionalEnv:
    - name: DOCKER_VERNEMQ_ACCEPT_EULA
      value: "yes"
    - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
      value: "on"
  podAntiAffinity: hard
