---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-data-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: nas-data-pvc
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.115
    path: "/kube-nfs"
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
