---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: nfs-data-pvc
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.50.108
    path: "/export/dell-nfs"
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zwave2mqtt
spec:
  storageClassName: nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: zwave2mqtt
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.50.110
    path: "/export/ha/zwave2mqtt"
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwave2mqtt
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-pvc
spec:
  storageClassName: nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: home-assistant-pvc
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.224
    path: "/export/ha/home-assistant-pvc"
  mountOptions:
    - nfsvers=3
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
