---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nas-data-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: nfs-nas-data-pvc
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.132
    path: "/export/nas"
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nas-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
